language: python
cache: pip
python:
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
before_install:
  - python3 -m pip install -U coverage codecov mypy
install:
  - python3 -m pip install -r requirements.txt
script:
  - python3 -m coverage run --branch -m unittest discover -t . -s ni/test/
  - python3 -m mypy ni
after_success:
  - codecov
